#ifndef QFWANKHLIB_GLOBAL_HPP
#define QFWANKHLIB_GLOBAL_HPP

#include <QtCore/qglobal.h>

#if defined(QFWANKHLIB_LIBRARY)
#  define QFWANKHLIBSHARED_EXPORT Q_DECL_EXPORT
#else
#  define QFWANKHLIBSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // QFWANKHLIB_GLOBAL_HPP
